### ISSUE TITLE
Amavis and BAD-HEADER-1

### ISSUE THREAD

**Issue by tech-otaku** [bambrikii/bash-examples#1]
Many thanks for this. I've been using it to email daily reports generated by pflogsumm. 

One issue I had though was Amavis  identifying the emails with `Passed BAD-HEADER-1` instead of `Passed CLEAN`. This was due to the MIME message end-marker missing. 

The final line of the script should be `--$BOUNDARY--" | sendmail -t` and not `--$BOUNDARY" | sendmail -t`. Note the addition of the two trailing dashes after `--$BOUNDARY--`

Regards, Steve.

**Comment by bambrikii** [comment]
hi Steve,

you're right. according to https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html , the last bounary needs to have two or more trailing hyphens:

> The encapsulation boundary following the last body part is a distinguished delimiter that indicates that no further body parts will follow. Such a delimiter is identical to the previous delimiters, with the addition of two more hyphens at the end of the line:
>
>     --gc0p4Jq0M2Yt08jU534c0p-- 

have updated the sample script:
https://github.com/bambrikii/bash-examples/blob/78c86e22cabacd30a3a50dc4477a5f83df512aa7/sendmail-sample-with-attachment-and-multiple-inline-contents.sh#L58

Thanks again

Regards,
Alexander
